stages:
<<<<<<< HEAD
    - build
    
rust-latest:
    stage: build
    image: rust:latest
    script:
        - cargo build --verbose
        
rust-nightly:
    stage: build
    image: rustlang/rust:nightly
    script:
        - cargo build --verbose
    allow_failure: true
=======
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
  allow_failure: true
>>>>>>> 6674fbfab0288b0d71f3c0d6cb17f805d619c002
